# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home_a
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - drive_wheel_left_joint
    - drive_wheel_right_joint
    - j2s6s200_joint_1
    - j2s6s200_joint_2
    - j2s6s200_joint_3
    - j2s6s200_joint_4
    - j2s6s200_joint_5
    - j2s6s200_joint_6
    - j2s6s200_joint_finger_1
    - j2s6s200_joint_finger_2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
controller_list:
  - name: j2s6s200
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j2s6s200_joint_1
      - j2s6s200_joint_2
      - j2s6s200_joint_3
      - j2s6s200_joint_4
      - j2s6s200_joint_5
      - j2s6s200_joint_6
  - name: j2s6s200_gripper
    action_ns: gripper_command
    default: True
    type: GripperCommand
    joints:
      - j2s6s200_joint_finger_1
      - j2s6s200_joint_finger_2