- name: "Default Zone"
  remove_surface: true
  parent_frame_id: "base_footprint"
  child_frame_id: "rs_depth_optical_frame"
  bounding_frame_id: "base_footprint"
  segmentation_frame_id: "base_footprint"
  z_min: -0.01
